## Teste de uma proporção

Taxa de fumantes em uma cidade era 21%. Uma amostra de 100 habitantes encontrou 14 fumantes. A proporção de fumantes da cidade mudou (nível de confiança = 95%)?

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import scipy.stats as stats

mudou = aumentado ou diminuído, por isso 2 caudas

hipóstese nula = as proporções não mudaram

H0: p = p0 \
HA: p ≠ p0

In [5]:
stats.binomtest(14, 100, p=0.21, alternative='two-sided')
#p value 0,1 que é mairo que 0.005, ou seja falhamos em rejeitart a hip nula

BinomTestResult(k=14.0, n=100.0, alternative='two-sided', statistic=0.14, pvalue=0.10920815720825913)

Conclusão:

Taxa de fumantes em uma cidade era 21%. Uma amostra de 100 habitantes encontrou 14 fumantes. A proporção de fumantes da cidade reduziu? (uma cauda – nível de confiança = 95%).

uma cauda só, a cauda esquerda, desconfiança vai para uma cauda 

a pergunta vai para a hipótese alternativa


a proporção não mudou, mas reduziu

H0: p >= p0 \
HA: p < p0

In [8]:
stats.binomtest(14, 100, p=0.21, alternative='less')
#deu 0.0504, um pouco acima
#1 erro a cada 20 testes?? aaaaaaaaaaaaaaaaaaaaaaa

BinomTestResult(k=14.0, n=100.0, alternative='less', statistic=0.14, pvalue=0.05042460221552124)

Conclusão: a pop não reduziu...?

Exercício 1 \
Uma empresa realizou uma campanha anti-tabagismo visando diminuir a proporção de seus trabalhadores que são fumantes. Sabe-se que antes da campanha 21% dos trabalhadores se declaravam fumantes. Para verificar se essa porcentagem mudou após a campanha, a empresa coletou informações de 100 funcionários e armazenou o resultado no arquivo Smokers.csv. Realize um teste de hipótese e informe se a proporção de fumantes continua a mesma ou mudou.

In [9]:
df = pd.read_csv('Smokers.csv')
df.head()

       Name Smokers
0  Person 1      No
1  Person 2      No
2  Person 3      No
3  Person 4     Yes
4  Person 5      No

In [11]:
fumantes = df.groupby('Smokers').count()
fumantes

         Name
Smokers
No         83
Yes        17

In [ ]:
num_fumantes = fumantes.loc['Yes'].values[0]

In [14]:

stats.binomtest(num_fumantes, 100, p=0.21, alternative='two-sided')

BinomTestResult(k=17.0, n=100.0, alternative='two-sided', statistic=0.17, pvalue=0.3900816892191661)

H0: p = p0 \
HA: p ≠ p0

Conclusão: o pvalue é 0.29, que é muito maior que 0.05, então falhamos em rejeitar a hipótese nula
a proporção não mudou

Exercício 2 \
Uma estimativa feita por um instituto de pesquisa apontou que 25% das mulheres que frequentam restaurantes numa dada cidade são fumantes. O dono de um restaurante decidiu testar uma amostra de suas clientes para verificar se esta estimativa é correta. Realize o teste de uma proporção com os dados contidos em 'tips.csv' e informe se a estimativa está correta (nível de confiança = 95%).

In [15]:
df = sns.load_dataset('tips')
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [32]:
mulheres = df[df['sex'] == 'Female'][['smoker','sex']]
mulheres.groupby('smoker').count()

        sex
smoker
Yes      33
No       54

In [33]:
num_fumantes = fumantes.loc['Yes'].values[0]

In [35]:
stats.binomtest(33, 87, p=0.25, alternative='two-sided')

BinomTestResult(k=33.0, n=87.0, alternative='two-sided', statistic=0.3793103448275862, pvalue=0.008747732318429478)

pValue<0.05, rejeitamos a hipótese nula, a proporção mudou

Conclusão:

Exercício 3 \
Uma empresa afirma que 70% dos seus clientes estão satisfeitos. Pesquisamos 100 clientes e descobrimos que 65 estão satisfeitos. Queremos testar se a verdadeira proporção de clientes satisfeitos é significativamente diferente de 70%. Confiança: 95%.

Apresente a solução: \
a) Em python; \
b) Utilizando a curva normal.

Conclusão: